### ISSUE TITLE
volume  changing crash

### ISSUE THREAD

**Issue by hjmeneses** [cg2121/obs-soundboard#1]
Doesn´t work for me, volume is set at the minimum, and trying to increase volume crashes obs

Thread 9ABC: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000B3090FA3E0 00007FF70D9DF96E 0000026F91DFFCF0 0000026F91DFFCF0 0000026F3CD54701 0000026F000100E0 obs64.exe!VolumeAccessibleInterface::text+0x2e
000000B3090FA420 00007FFDFA6A8009 0000026F6BEFE4E0 0000026F91DFFCF0 0000026F000100E0 000000B3090FA520 qwindows.dll!0x7ffdfa6a8009
000000B3090FA4D0 00007FFD8BB64A62 0000026F6C57C410 0000026F6C57C410 0000026F000100E0 00007FFE5133F05B qt5gui.dll!0x7ffd8bb64a62
000000B3090FA500 00007FFD8C1D26E9 0000026F52DF2420 00007FFD00000000 0000026F6BCEA140 0000000000000000 qt5widgets.dll!0x7ffd8c1d26e9
000000B3090FA550 00007FFDDFC52F35 0000026F6BEF0020 0000026F6BEFDDB0 0000026F38F630E0 0000026F6BCEA140 obs-soundboard.dll!VolControl::updateText+0x155
000000B3090FA5B0 00007FFD89DF0B37 0000026F6C57C410 0000026F00000007 0000026F5356A400 0000000000000001 qt5core.dll!0x7ffd89df0b37
000000B3090FA700 00007FFD8C271FE0 0000026F5356A400 00007F010000001E 000000000000001E 0000000A00000001 qt5widgets.dll!0x7ffd8c271fe0
000000B3090FA770 00007FFD8C271EAC 000000000000011B 0000000000000113 0000000000000113 0000000000000005 qt5widgets.dll!0x7ffd8c271eac
000000B3090FA7B0 00007FFD8C307FA3 0000011900000008 0000026F3CD9BFE0 0000026F6C57C410 0000026F3CD9CC40 qt5widgets.dll!0x7ffd8c307fa3
000000B3090FA8B0 00007FFD8C1C77FC 0000026F3CD9BFE0 0000026F3CD9BFE0 000000B3090FB240 000000B3090FB240 qt5widgets.dll!0x7ffd8c1c77fc
000000B3090FA940 00007FFD8C1A4980 000000B3090FB240 000000B3090FAA70 0000000000000000 000000B3090FAA70 qt5widgets.dll!0x7ffd8c1a4980
000000B3090FA970 00007FFD8C1A28A0 0000000000000000 0000026F3CD54760 000000B3090FB240 0000026F3CD54760 qt5widgets.dll!0x7ffd8c1a28a0
000000B3090FAEB0 00007FFD89DD19CA 3FF0000000000000 0000000000000000 0000000000000000 3FF0000000000000 qt5core.dll!0x7ffd89dd19ca
000000B3090FAF20 00007FFD8C1A5B85 0000000000000000 0000026F6C57C410 0000000000000000 0000026F8C385160 qt5widgets.dll!0x7ffd8c1a5b85
000000B3090FAFE0 00007FFD8C1F00DB 0000026F9BA17060 00007FFE53A147B1 0000000000000000 0000026F3CD40000 qt5widgets.dll!0x7ffd8c1f00db
000000B3090FB370 00007FFD8C1EE0A4 0000026F3CD9BFE0 0000026F3CD9CC40 000000B3090FBD20 0000026F5914BC00 qt5widgets.dll!0x7ffd8c1ee0a4
000000B3090FB440 00007FFD8C1A4980 0000026F3CD9BFE0 000000B3090FB570 00007FFD8C190000 00007FFD89EF7D10 qt5widgets.dll!0x7ffd8c1a4980
000000B3090FB470 00007FFD8C1A3A03 0000026F3CD9E950 0000026F3CD54760 000000B3090FBD20 0000026F3CD54760 qt5widgets.dll!0x7ffd8c1a3a03
000000B3090FB9B0 00007FFD89DD19CA 0000026F3CD9E950 0000000000000002 0000026F3CD9E950 0000000000000000 qt5core.dll!0x7ffd89dd19ca
000000B3090FBA20 00007FFD8BB83086 00007FFD8C139688 0000000000000024 0000000000000001 0000026FA4AF92E0 qt5gui.dll!0x7ffd8bb83086
000000B3090FBED0 00007FFD8BB6ECE0 0000000000000000 00007FFD8C139688 000000B3090FC000 0000026FA4FB18D0 qt5gui.dll!0x7ffd8bb6ece0
000000B3090FBF00 00007FFD89E1A83A 0000026F3CD9E450 0000000000000000 0000026FA4FB18D0 0000000000000000 qt5core.dll!0x7ffd89e1a83a
000000B3090FF020 00007FFDFA6B2619 0000000000000000 00007FFD00000014 0000000000000000 0000000000000040 qwindows.dll!0x7ffdfa6b2619
000000B3090FF050 00007FFD89DCDE7C 0000026F3CD4CFB8 0000000000000000 000000B3090FF5F0 00007FFD89EEFC90 qt5core.dll!0x7ffd89dcde7c
000000B3090FF0B0 00007FFD89DD0994 00007FF70DB540F0 000000B3090FF530 00007FF70DB540F0 000000B3090FF5F0 qt5core.dll!0x7ffd89dd0994
000000B3090FF110 00007FF70D8986B4 0000000000000000 0000026F3CD84060 0000026F00000000 0000026F3CD81C80 obs64.exe!run_program+0xa04
000000B3090FF4F0 00007FF70D89A980 0000000000000000 0000000000000000 0000000000000000 FFFFFFFFFFFFFFFF obs64.exe!main+0x6f0
000000B3090FF6C0 00007FF70DA374A7 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!WinMain+0x157
000000B3090FF750 00007FF70DA36D66 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!__scrt_common_main_seh+0x106
000000B3090FF790 00007FFE51DE7034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffe51de7034
000000B3090FF7C0 00007FFE53A42651 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffe53a42651

**Comment by cg2121** [comment]
Could you confirm the latest release fixes your issue?
https://github.com/cg2121/obs-soundboard/releases/tag/1.0.1

**Comment by hjmeneses** [comment]
i´m afraid it did not, this is my latest crash log

https://obsproject.com/logs/zsoENkWd9HfmZH0N

best regards
Hector J. Meneses Lavalley

**Comment by cg2121** [comment]
Could you also post the OBS log?

**Comment by hjmeneses** [comment]
Sure, anything i can do to help

https://obsproject.com/logs/bNPNLxxt5zw-q0F2

i was able to make it useful editing my json scene file and it works great,
i just need to avoid touching the volume

best regards
Hector J. Meneses Lavalley

**Comment by cg2121** [comment]
Now try this one
https://github.com/cg2121/obs-soundboard/releases/tag/1.0.2

**Comment by hjmeneses** [comment]
kt worked! volume is availiable now, awesome!
Hector J. Meneses Lavalley
