### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by datlaunchystark** [cg2121/obs-soundboard#2]
Worked for a little bit then had to remove to get OBS to startup correctly.
OBS 27.2 Windows 10 21H2

[Crash 2022-02-20 13-25-39.txt](https://github.com/cg2121/obs-soundboard/files/8104950/Crash.2022-02-20.13-25-39.txt)
[2022-02-20 13-25-30.txt](https://github.com/cg2121/obs-soundboard/files/8104951/2022-02-20.13-25-30.txt)

**Comment by cg2121** [comment]
Could you confirm the latest release fixes your issue?
https://github.com/cg2121/obs-soundboard/releases/tag/1.0.1

**Comment by datlaunchystark** [comment]
OMG thx so much!  So far no crashes yet.  Will update if I encounter any :)
