### ISSUE TITLE
Can't add Dock, Mac

### ISSUE THREAD

**Issue by Whitezd01** [cg2121/obs-soundboard#4]
Running M1 Mac Monterey 12.3.1 and OBS Verision 27.2.4. I installed on my mac like usual and now I can't find where the download went. Almost like it never happened. When I open OBS and go to add the dock, I don't see the option to add a soundboard as a dock either.

**Comment by juanalbertosm** [comment]
I have the same problem. Soundboard is nowhere to be seen on Mac Catalina… Does anyone know of a solution? Thank you.

**Comment by dmyers** [comment]
Same on Monterey.

**Comment by cg2121** [comment]
Should be fixed in next release.
