### ISSUE TITLE
Flatpak Installation?

### ISSUE THREAD

**Issue by ItsRogueRen** [cg2121/obs-soundboard#6]
The only provided release for Linux is a deb file, is there a way to install this on the OBS flatpak (which is an officially supported OBS release) that doesn't require compiling from source?

**Comment by cg2121** [comment]
Should request feature at https://github.com/obsproject/obs-plugintemplate, as this is based on that.

**Comment by ItsRogueRen** [comment]
...what? Are you saying I should ask OBS Project to make your plugin work on the flatpak? How does that make sense?

**Comment by cg2121** [comment]
Yes. OBS has a plugin template for developers to use to make plugins, which this is based off of. If they add it there it would be available for all plugins not just this one.
