### ISSUE TITLE
Crashes the V28 OBS

### ISSUE THREAD

**Issue by OGNetheri** [cg2121/obs-soundboard#8]
EDIT: There's also some clipping on sound effects playing which wasn't present on earlier versions. Every time OBS V28 is closed, it crashes and I checked the crashlog. Culprit is the obs-soundboard.dll : 

Unhandled exception: c0000005
Date/Time: 2022-09-04, 14:59:56
Fault address: 7FFCDC7E9A18 (d:\program files\obs-studio\obs-plugins\64bit\obs-soundboard.dll)
libobs version: 28.0.1 (64-bit)
Windows version: 10.0 build 19044 (release: 2009; revision: 1949; 64-bit)
CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

Thread 2CFC: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
0000002A9C2F9F80 00007FFCDC7E9A18 03E88CB3C9484E2B 0000022419493B88 00000224678F07C0 00007FFD0E5347B1 obs-soundboard.dll!SceneTree::selectionChanged+0x48
0000002A9C2F9FD0 00007FFC8BB8952E 0000022419101F70 0000000000000003 0000000000000003 0000022408829601 qt6core.dll!0x7ffc8bb8952e
0000002A9C2FA130 00007FFC8BB8B9A4 0000022407EA4680 0000002A9C2FA260 00000000FFFFFFFF 000002241909B3B0 qt6core.dll!0x7ffc8bb8b9a4
0000002A9C2FA160 00007FFC8BD38327 03E88CB3C9484E2B 0000022400000000 0000002A9C2FA7C0 000002241909B430 qt6core.dll!0x7ffc8bd38327
0000002A9C2FA610 00007FFC8BB8952E 0000022407D38610 00007FFC0000000E 0000000000000003 0000022407D38601 qt6core.dll!0x7ffc8bb8952e
0000002A9C2FA770 00007FFC8BB8B9A4 0000000000000000 0000000000000000 0000000000000000 0000000000000000 qt6core.dll!0x7ffc8bb8b9a4
0000002A9C2FA7A0 00007FFC8BD21C8B 0000000000000001 FFFFFFFFFFFFFFFF 0000000000000000 0000000000000000 qt6core.dll!0x7ffc8bd21c8b
0000002A9C2FA850 00007FFC8C2DD9E5 0000000000000019 0000022419153620 0000022422368230 0000000000000000 qt6widgets.dll!0x7ffc8c2dd9e5
0000002A9C2FA8A0 00007FFCDC7EB055 0000000000000000 0000022419153620 00000224222F3A80 000000000000000D obs-soundboard.dll!QListWidgetItem::`scalar deleting destructor'+0x15
0000002A9C2FA8D0 00007FFCDC7EB546 000000000000000D 0000000000000019 0000022402144FA0 00000000000000D0 obs-soundboard.dll!Soundboard::ClearSoundboard+0xc6
0000002A9C2FA920 00007FF70F79D680 0000000000000000 0000022402210E50 0000000000000000 0000022402210E50 obs64.exe!OBSStudioAPI::on_event+0x70
0000002A9C2FA950 00007FF70F814397 0000022400000001 000002247E47D8A0 0000022422767370 0000022402210E50 obs64.exe!OBSBasic::ClearSceneData+0x2d7
0000002A9C2FA9B0 00007FF70F839144 0000000000000000 0000002A9C2FBB00 000002247E490220 0000002A9C2FBB00 obs64.exe!OBSBasic::closeEvent+0x634
0000002A9C2FB490 00007FFC8C07DE45 000002247E490220 000002247E490220 000002247E490220 0000022402210E50 qt6widgets.dll!0x7ffc8c07de45
0000002A9C2FB570 00007FFC8C0414AE 000002247E490220 0000002A9C2FB6A0 0000000000000000 000002247E490220 qt6widgets.dll!0x7ffc8c0414ae
0000002A9C2FB5A0 00007FFC8C040674 0000002A9C2FF840 0000022402210E50 0000002A9C2FBB00 0000000000000000 qt6widgets.dll!0x7ffc8c040674
0000002A9C2FBA70 00007FFC8BB50505 00000000000000E0 000002247E540CC0 0000022402210E50 0000000000000000 qt6core.dll!0x7ffc8bb50505
0000002A9C2FBAE0 00007FFC8C07FDF0 0000002A9C2FC310 0000002A9C2FBC09 00000224021453C0 0000002A9C2FC310 qt6widgets.dll!0x7ffc8c07fdf0
0000002A9C2FBB20 00007FFC8C0987EC 0000022402239250 0000000000000000 0000000000000002 00007FFC98F9F9DE qt6widgets.dll!0x7ffc8c0987ec
0000002A9C2FBB50 00007FFC98FB22D8 000002247E49C530 00007FFD0E535BA1 00000224021453C0 0000000000000000 qt6gui.dll!0x7ffc98fb22d8
0000002A9C2FBC70 00007FFC8C0992A8 000002247E490220 000002247E4A6BE0 000002247E490220 0000002A9C2FC310 qt6widgets.dll!0x7ffc8c0992a8
0000002A9C2FBD80 00007FFC8C0414AE 000002247E490220 0000002A9C2FBEB0 0000000000000000 000002247E490220 qt6widgets.dll!0x7ffc8c0414ae
0000002A9C2FBDB0 00007FFC8C040674 0000002A9C2FF840 00000224021453C0 0000002A9C2FC310 0000022400000000 qt6widgets.dll!0x7ffc8c040674
0000002A9C2FC280 00007FFC8BB50505 0000000000000000 00007FFC98F6BBB1 00000224678EFB90 0000002A00000000 qt6core.dll!0x7ffc8bb50505
0000002A9C2FC2F0 00007FFC98F72F19 00000224678EFB90 00000224675B0060 0000000000000000 00000000000000A4 qt6gui.dll!0x7ffc98f72f19
0000002A9C2FC330 00007FFC98FC03E8 00000000000000A4 000002247E4BED20 000002247E4BED20 0000000000000000 qt6gui.dll!0x7ffc98fc03e8
0000002A9C2FC360 00007FFC8BCA3F04 0000000000000000 0000000000000000 0000022424D16CD0 000002247E4BB310 qt6core.dll!0x7ffc8bca3f04
0000002A9C2FF4D0 00007FFC991D0FA9 00000000000000A4 0000000000000080 0000022424D16CD0 000002247E490220 qt6gui.dll!0x7ffc991d0fa9
0000002A9C2FF500 00007FFC8BB55874 0000002A9C2FF5C0 000002247E44CB80 000002247E44CB80 0000002A9C2FFA60 qt6core.dll!0x7ffc8bb55874
0000002A9C2FF5A0 00007FFC8BB4E57D FFFFFFFFFFFFFFFF 00007FF70F9D4748 FFFFFFFFFFFFFFFF 0000002A9C2FFA60 qt6core.dll!0x7ffc8bb4e57d
0000002A9C2FF600 00007FF70F7961B0 0000000000000000 000002247E47D720 0000022400000000 0000000000000001 obs64.exe!run_program+0xb20
0000002A9C2FF960 00007FF70F7989A0 0000000000000000 0000000000000000 0000000000000000 FFFFFFFFFFFFFFFF obs64.exe!main+0x6d0
0000002A9C2FFB30 00007FF70F9A4B27 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!WinMain+0x157
0000002A9C2FFBC0 00007FF70F9A42B2 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!__scrt_common_main_seh+0x106
0000002A9C2FFC00 00007FFD0D6D7034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffd0d6d7034
0000002A9C2FFC30 00007FFD0E5626A1 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffd0e5626a1

**Comment by cg2121** [comment]
Fixed with https://github.com/cg2121/obs-soundboard/commit/6db11dd01d384cbd18d857f0812f730d6e84ecab

**Comment by OGNetheri** [comment]
> Fixed with [6db11dd](https://github.com/cg2121/obs-soundboard/commit/6db11dd01d384cbd18d857f0812f730d6e84ecab)

So err..in which file where should I make the fix in the code?
