### ISSUE TITLE
obs-soundboard 1.1.0 for Linux is linked against Qt6 but packaging requires Qt5

### ISSUE THREAD

**Issue by flexiondotorg** [cg2121/obs-soundboard#9]
The `debiasn/control` file in the obs-soundboard 1.1.0 .deb depends on Qt5 but `obs-soundboard.so` is linked against Qt6.

Please change `/debian/control` as follows: 

 - **From:** `Depends: obs-studio (>= 27.0.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.3.0), libqt5widgets5 (>= 5.7.0)`

 - **To:** `Depends: obs-studio (>= 28.0.0), libqt6core6 (>= 6.2.0), libqt6gui6 (>= 6.1.2), libqt6widgets6 (>= 6.1.2)`

**Comment by cg2121** [comment]
I will make sure to change it. It would also be good for you to report the issue it to the https://github.com/obsproject/obs-plugintemplate repo, as this is based off of that.
